name = "LorentzVectorHEP"
uuid = "f612022c-142a-473f-8cfd-a09cf3793c6c"
authors = ["Jerry Ling <proton@jling.dev> and contributors"]
version = "0.1.6"

[deps]
LorentzVectorsBase = "592a752d-6533-4762-a71b-738712ea30ec"
LorentzVectors = "3f54b04b-17fc-5cd4-9758-90c048d965e3"

[compat]
LorentzVectorBase = "^0.1"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
